language: php
php:
  - '5.6'

install:
  composer install

script:
  - wget https://phar.phpunit.de/phpunit.phar
  - chmod +x phpunit.phar 
  - sudo mv phpunit.phar /usr/local/bin/phpunit 
  - phpunit --version 
  - phpunit