version: 2
jobs:
  build:
    working_directory: ~/circulate
    docker:
      - image: alexwijn/docker-git-php-composer
    steps:
      - checkout
      - run:
          name: Run tests
          command: phpunit